{ config
, lib
, pkgs
, ...
}:
let
  hyprConfigDir = "${config.xdg.configHome}/hypr";
  monitorsLua = "${hyprConfigDir}/monitors.lua";

  # hyprmoncfg only rewrites a target it owns
  monitorsLuaSeed = pkgs.writeText "monitors.lua" ''
    -- Generated by hyprmoncfg
  '';
in
{
  home.packages = [ pkgs.hyprmoncfg ];

  xdg.configFile."hyprmoncfg/profiles" = {
    source = ./profiles;
    recursive = true;
    # `recursive` symlinks each profile individually
    # instead of the whole directory, so `hyprmoncfg` can still save ad-hoc
    # profiles alongside them
  };

  wayland.windowManager.hyprland.extraConfig = ''
    -- Monitor layout is generated into monitors.lua by hyprmoncfg/hyprmoncfgd.
    require("monitors")
  '';

  # require() hard-errors on a missing module, which would take the whole
  # Hyprland config down before hyprmoncfg ever gets to write monitors.lua.
  # Seed a marker-only file so the first apply can claim it.
  # home.activation.hyprmoncfgSeedMonitors = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
  #   if [ ! -e "${monitorsLua}" ]; then
  #     run install -Dm644 ${monitorsLuaSeed} "${monitorsLua}"
  #   fi
  # ''; TODO: check if this is needed, I don't think it is.

  systemd.user.services.hyprmoncfgd = {
    Unit = {
      Description = "Hyprland monitor profile daemon (hyprmoncfgd)";
      PartOf = [ "graphical-session.target" ];
      After = [ "graphical-session.target" ];
    };
    Service = {
      Type = "simple";
      ExecStart = "${pkgs.hyprmoncfg}/bin/hyprmoncfgd";
      Environment = [
        "PATH=${lib.makeBinPath [ config.wayland.windowManager.hyprland.finalPackage ]}"
      ];
      Restart = "on-failure";
      RestartSec = 2;
    };
    Install.WantedBy = [ "graphical-session.target" ];
  };
}
