{ config
, lib
, pkgs
, ...
}:
let
  hyprConfigDir = "${config.xdg.configHome}/hypr";
  monitorsLua = "${hyprConfigDir}/monitors.lua";

  # hyprmoncfg only rewrites a target it owns
  monitorsLuaSeed = pkgs.writeText "monitors.lua" ''
    -- Generated by hyprmoncfg
  '';
in
{
  home.packages = [ pkgs.hyprmoncfg ];

  xdg.configFile."hyprmoncfg/profiles" = {
    source = ./profiles;
    recursive = true;
    # `recursive` symlinks each profile individually
    # instead of the whole directory, so `hyprmoncfg` can still save ad-hoc
    # profiles alongside them
  };

  wayland.windowManager.hyprland.extraConfig = ''
    -- Monitor layout is generated into monitors.lua by hyprmoncfg/hyprmoncfgd.
    require("monitors")
  '';

  systemd.user.services.hyprmoncfgd = {
    Unit = {
      Description = "Hyprland monitor profile daemon (hyprmoncfgd)";
      PartOf = [ "graphical-session.target" ];
      After = [ "graphical-session.target" ];
    };
    Service = {
      Type = "simple";
      ExecStart = "${pkgs.hyprmoncfg}/bin/hyprmoncfgd";
      Environment = [
        "PATH=${lib.makeBinPath [ config.wayland.windowManager.hyprland.finalPackage ]}"
      ];
      Restart = "on-failure";
      RestartSec = 2;
    };
    Install.WantedBy = [ "graphical-session.target" ];
  };
}
