monitorv2 {
  output = desc: Lenovo Group Limited E24-30 VNAA0DF4
  mode = 1920x1080@60.00000
  position = 0x0
  scale = 1
}

monitorv2 {
  output = desc: Dell Inc. DELL P2417H CW6Y77720YVI
  mode = 1920x1080@60.00000
  position = 1920x0
  scale = 1
}

monitorv2 {
  output = eDP-1
  disabled = true
}