{ config
, lib
, pkgs
, ...
}:
let
  cfg = config.services.shader-desk;

  toLua = lib.generators.toLua { };
  mkLuaInline = lib.generators.mkLuaInline;

  # Polls Hyprland for the cursor and speaks the engine's pointer datagram, so
  # the evdev daemon (and with it, membership in the "input" group) is not
  # needed. See the script for the wire format.
  cursor-daemon = pkgs.writers.writePython3Bin "shader-desk-hyprland-cursor" { }
    (builtins.readFile ./hyprland-cursor.py);

  # Hyprland has no IPC for button state, so the binds below poke the daemon
  # directly. Failing quietly matters: these run on every click, including
  # while shader-desk is stopped.
  cursor-button = pkgs.writeShellApplication {
    name = "shader-desk-cursor-button";
    runtimeInputs = [ pkgs.socat ];
    text = ''
      socket="''${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/shader-desk-cursor.sock"
      printf '%s' "''${1:-}" | socat -u - "UNIX-SENDTO:$socket" 2>/dev/null || true
    '';
  };

  clickBind = state: mkLuaInline
    "hl.dsp.exec_cmd(${toLua "${cursor-button}/bin/shader-desk-cursor-button ${state}"})";

  defaultProviders = {
    # The name is the C++ provider's, not the daemon's: it is the plugin that
    # owns $XDG_RUNTIME_DIR/shader-desk-pointer.sock, whoever feeds it.
    "Evdev Pointer Provider" = {
      enabled = true;
      mouse_sensitivity = 10.0;
      touchpad_sensitivity = 10.0;
      invert_x = false;
      invert_y = false;
    };

    "Native FFTW Audio Provider" = {
      enabled = cfg.audio.enable;
      smoothing = 0.85;
      volume_multiplier = 1.0;
      bass_multiplier = 1.0;
      mid_multiplier = 1.0;
      treble_multiplier = 100.0;
    };
  };

  providersLua = ''
    -- Generated by home-manager; changes here are lost on the next switch.
    _G.core = _G.core or {}

    -- Scenes address hardware events through these constants rather than raw
    -- strings, so the registry has to exist before any scene is loaded.
    core.events = require("events")

    core.events.register_types("AUDIO", {
      BASS_KICK = "audio.bass_kick",
      BEAT      = "audio.beat",
      SILENCE   = "audio.silence"
    })

    core.events.register_types("POINTER", {
      CLICK  = "pointer.click",
      SCROLL = "pointer.scroll"
    })

    core.providers = ${toLua (lib.recursiveUpdate defaultProviders cfg.providers)}

    return core.providers
  '';

  outputs = { "*" = cfg.scene; } // cfg.outputs;

  routing = lib.concatStringsSep "\n" (lib.mapAttrsToList
    (output: scene: "  [${toLua output}] = core.load_scene(${toLua scene}),")
    outputs);

  initLua = ''
    -- Generated by home-manager; changes here are lost on the next switch.
    _G.core = _G.core or {}
    _G.ctl = require("ctl")

    require("providers")

    -- Wayland output name -> scene. "*" catches every unnamed display.
    core.outputs = {
    ${routing}
    }

    -- Hand the core's per-output triggers to whichever scene that output runs.
    core.register_lifecycle({
      on_init = function(output_name)
        local scene = core.outputs[output_name] or core.outputs["*"]
        if scene and type(scene.on_init) == "function" then
          scene:on_init(output_name)
        end
      end,

      on_update = function(dt, output_name)
        -- A frame time this long means the session was asleep, not that the
        -- scene should integrate a huge step and fling itself apart.
        if dt > 0.1 then dt = 0.0166 end

        local scene = core.outputs[output_name] or core.outputs["*"]
        if scene and type(scene.on_update) == "function" then
          scene:on_update(dt, output_name)
        end
      end,

      on_destroy = function(output_name)
        local scene = core.outputs[output_name] or core.outputs["*"]
        if scene and type(scene.on_destroy) == "function" then
          scene:on_destroy(output_name)
        end
      end,

      on_save_state = function(output_name)
        local scene = core.outputs[output_name] or core.outputs["*"]
        if scene and type(scene.on_save_state) == "function" then
          return scene:on_save_state(output_name)
        end
        return nil
      end,

      on_restore_state = function(output_name, saved_data)
        local scene = core.outputs[output_name] or core.outputs["*"]
        if scene and type(scene.on_restore_state) == "function" then
          scene:on_restore_state(saved_data, output_name)
        end
      end
    })
  '';
in
{
  options.services.shader-desk = {
    enable = lib.mkEnableOption "shader-desk, an interactive Wayland wallpaper engine";

    package = lib.mkOption {
      type = lib.types.package;
      description = "The shader-desk package to run.";
    };

    scene = lib.mkOption {
      type = lib.types.str;
      default = "01_liquid_mesh";
      example = "orbital_harmonics";
      description = ''
        Scene rendered on every output that {option}`services.shader-desk.outputs`
        does not name. Resolved against
        {file}`$XDG_CONFIG_HOME/interactive-wallpaper/scenes` first and the
        scenes embedded in the package second.
      '';
    };

    outputs = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = { };
      example = {
        "DP-2" = "synthwave_demo";
      };
      description = "Per-output scene overrides, keyed by Wayland output name.";
    };

    providers = lib.mkOption {
      type = with lib.types; attrsOf (attrsOf (oneOf [ bool int float str ]));
      default = { };
      example = {
        "Evdev Pointer Provider".mouse_sensitivity = 4.0;
      };
      description = ''
        Data provider settings, merged over the defaults and written to
        {file}`$XDG_CONFIG_HOME/interactive-wallpaper/providers.lua`. Keyed by
        the provider name reported by `interactive-wallpaper --list-providers`.
      '';
    };

    audio = {
      enable = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = ''
          Run the FFT daemon that feeds the audio spectrum to scenes reacting
          to sound.
        '';
      };
    };

    hyprland = {
      enable = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = ''
          Report the cursor to shader-desk by polling Hyprland instead of
          running the upstream evdev daemon. The evdev daemon reads
          {file}`/dev/input` directly, which needs the user in the `input`
          group and only ever yields relative hardware deltas; Hyprland knows
          the real cursor position and needs no extra privileges.
        '';
      };

      pollRate = lib.mkOption {
        type = lib.types.ints.positive;
        default = 60;
        description = "Hyprland cursor queries per second.";
      };

      mouseButtons = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = ''
          Report left mouse button state as well, through non-consuming
          Hyprland binds that leave the click itself untouched. Only scenes
          built on the ShaderToy sandbox read it, through `iMouse.zw`.
        '';
      };
    };

    systemd.target = lib.mkOption {
      type = lib.types.str;
      default = config.wayland.systemd.target;
      defaultText = lib.literalExpression "config.wayland.systemd.target";
      description = "Systemd user target the engine is bound to.";
    };
  };

  config = lib.mkIf cfg.enable {
    home.packages = [ cfg.package ];

    xdg.configFile = {
      "interactive-wallpaper/init.lua".text = initLua;
      "interactive-wallpaper/providers.lua".text = providersLua;
    };

    systemd.user.services.shader-desk = {
      Unit = {
        Description = "Shader Desk - interactive Wayland wallpaper engine";
        Documentation = "https://github.com/KMartianov/shader-desk";
        PartOf = [ cfg.systemd.target ];
        After = [ cfg.systemd.target ];
        ConditionEnvironment = "WAYLAND_DISPLAY";
        X-Restart-Triggers = [
          "${config.xdg.configFile."interactive-wallpaper/init.lua".source}"
          "${config.xdg.configFile."interactive-wallpaper/providers.lua".source}"
        ];
      };

      Service = {
        # Not shader-desk-run: that wrapper forks the daemons itself and pkills
        # anything that looks like an older instance, both of which systemd
        # already does, and better. The core takes the flock on its own.
        ExecStart = "${cfg.package}/bin/interactive-wallpaper";
        Restart = "on-failure";
        RestartSec = 3;
      };

      Install.WantedBy = [ cfg.systemd.target ];
    };

    systemd.user.services.shader-desk-audio = lib.mkIf cfg.audio.enable {
      Unit = {
        Description = "Shader Desk audio spectrum daemon";
        PartOf = [ "shader-desk.service" ];
        After = [ "shader-desk.service" ];
      };

      Service = {
        ExecStart = "${cfg.package}/bin/audio-daemon";
        Restart = "on-failure";
        RestartSec = 3;
      };

      Install.WantedBy = [ "shader-desk.service" ];
    };

    systemd.user.services.shader-desk-cursor = lib.mkIf cfg.hyprland.enable {
      Unit = {
        Description = "Hyprland cursor bridge for Shader Desk";
        PartOf = [ "shader-desk.service" ];
        After = [ "shader-desk.service" ];
        ConditionEnvironment = "HYPRLAND_INSTANCE_SIGNATURE";
      };

      Service = {
        # Datagrams are addressed per send, so the bridge survives the engine
        # restarting underneath it without needing to be restarted itself.
        ExecStart = "${cursor-daemon}/bin/shader-desk-hyprland-cursor --rate ${toString cfg.hyprland.pollRate}";
        Restart = "on-failure";
        RestartSec = 3;
      };

      Install.WantedBy = [ "shader-desk.service" ];
    };

    wayland.windowManager.hyprland.settings.bind =
      lib.mkIf (cfg.hyprland.enable && cfg.hyprland.mouseButtons) [
        # non_consuming keeps the click going to the window under the cursor;
        # we only get told that it happened.
        { _args = [ "mouse:272" (clickBind "1") { non_consuming = true; } ]; }
        { _args = [ "mouse:272" (clickBind "0") { non_consuming = true; release = true; } ]; }
      ];
  };
}
